version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install

workflows:
  commit-workflow:
    jobs:
      - lint_and_test
